; ----------------------------------------------------------------------------
; MARVELL INTERNATIONAL LTD., ON BEHALF OF ITSELF AND ITS WORLDWIDE 
; AFFILIATES(COLLECTIVELY, "MARVELL"), MAKES NO WARRANTY OF ANY KIND WITH 
; REGARD TO THIS MATERIAL, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES 
; OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
; MARVELL ASSUMES NO RESPONSIBILITY FOR ANY ERRORS THAT MAY
; APPEAR IN THIS DOCUMENT. MARVELL MAKES NO COMMITMENT TO
; UPDATE NOR TO KEEP CURRENT THE INFORMATION CONTAINED IN THIS DOCUMENT.
; ----------------------------------------------------------------------------
[Parser]
Operators =!%&()*+,-./:;<=>?[]^{|}~
Delimiters =!"#$%&'()*+,-./:;<=>?@[\]^`{|}~
KWStartChars =#
KWMiddleChars =
KWEndChars = 
NumTags =4

[Tag1]
ColorGroup =String
BeginTag ="
EndTag ="
MultiLine =0
EscapeChar=\

[Tag2]
ColorGroup =Comment
BeginTag =//
EndTag=
EscapeChar=
MultiLine=0

[Tag3]
ColorGroup =String
BeginTag ='
EndTag ='
EscapeChar=\
MultiLine=0

[Tag4]
ColorGroup =Comment
BeginTag =/*
EndTag =*/
EscapeChar=
MultiLine=1

[Editor]
TabSize =4
AutoIndent =0
ShowWhitespace =0
VirtualWhitespace =0
ReplaceTabs =0
MatchCase=1

[Font]
FaceName =Courier
Size =10
Italic =0
Bold =0

[ColorGroups]
NumGroups =9
Group1 =Text
Group2 =Text Selection
Group3 =Number
Group4 =Operator
Group5 =Keyword
Group6 =Comment
Group7 =String
Group8 =C
Group9 =CXX

[Text]
Foreground =0,0,0
Background =255,255,255
ForeColorAutomatic=0
BackColorAutomatic=0
DisplayName=Text
Configurable=1

[Text Selection]
Foreground=255,255,255
ForeColorAutomatic=0
Background=0,0,0
BackColorAutomatic=0
DisplayName=Text Selection
Configurable=1

[Keyword]
Foreground =0,0,255
Background =255,255,255
ForeColorAutomatic=0
BackColorAutomatic=0
DisplayName=Keyword
Configurable=1

[Operator]
Foreground =0,0,255
Background =255,255,255
ForeColorAutomatic=0
BackColorAutomatic=0
DisplayName=Operator
Configurable=1

[Comment]
Foreground =0,128,0
Background =255,255,255
ForeColorAutomatic=0
BackColorAutomatic=0
DisplayName=Comment
Configurable=1

[String]
Foreground =255,0,0
Background =255,255,255
ForeColorAutomatic=0
BackColorAutomatic=0
DisplayName=String
Configurable=1

[Number]
Foreground =0,0,0
Background =255,255,255
ForeColorAutomatic=0
BackColorAutomatic=0
DisplayName=Number
Configurable=1

[C]
Foreground =0,0,255
Background =255,255,255
ForeColorAutomatic=0
BackColorAutomatic=0
DisplayName=C
Configurable=1

[CXX]
Foreground =128,0,128
ForeColorAutomatic=0
Background=255,255,255
BackColorAutomatic=1
DisplayName=CXX
Configurable=1

[Keywords]
#elif=Keyword
#define=Keyword
#else=Keyword
#endif=Keyword
#ifndef=Keyword
#if=Keyword
#ifdef=Keyword
#include=Keyword
try=CXX
reinterpret_cast=CXX
delete=CXX
truew=CXX
friend=CXX
throw=CXX
public=CXX
wchar_t=CXX
this=CXX
protected=CXX
const_cast=CXX
template=CXX
private=CXX
false=CXX
operator=CXX
class=CXX
virtual=CXX
new=CXX
export=CXX
using=CXX
static_cast=CXX
namespace=CXX
explicit=CXX
catch=CXX
mutable=CXX
typename=CXX
dynamic_cast=CXX
typeid=CXX
inline=CXX
asm=CXX
do=Keyword
if=Keyword
return=Keyword
typedef=Keyword
auto=Keyword
double=Keyword
inline= CXX
short=Keyword
bool=Keyword
int=Keyword
signed=Keyword
else=Keyword
long=Keyword
sizeof=Keyword
union=Keyword
case=Keyword
enum=Keyword
mutable=CXX
static=Keyword
unsigned=Keyword
char=Keyword
struct=Keyword
extern=Keyword
switch=Keyword
void=Keyword
const=Keyword
volatile=Keyword
float=Keyword
continue=Keyword
for=Keyword
while=Keyword
default=Keyword
register=Keyword
goto=Keyword
break=Keyword

while=Keyword
if=Keyword
entry=Keyword
goto=Keyword
const=Keyword
volatile=Keyword
switch=Keyword
float=Keyword
double=Keyword
sizeof=Keyword
default=Keyword
near=Keyword
int=Keyword
chill=Keyword
typedef=Keyword
else=Keyword
signed=Keyword
continue=Keyword
break=Keyword
do=Keyword
soft=Keyword
for=Keyword
void=Keyword
alien=Keyword
struct=Keyword
readonly=Keyword
long=Keyword
char=Keyword
far=Keyword
extern=Keyword
case=Keyword
auto=Keyword
enum=Keyword
unsigned=Keyword
short=Keyword
static=Keyword
union=Keyword
return=Keyword
register=Keyword

in		=Keyword
inhword		=Keyword
inl		=Keyword
inword		=Keyword
inb		=Keyword
inbyte		=Keyword
out		=Keyword
outhword	=Keyword
outl		=Keyword
outword		=Keyword
outb		=Keyword
outbyte		=Keyword
cli		=Keyword
disable		=Keyword
sti		=Keyword
enable		=Keyword
strcpy		=Keyword
abs		=Keyword
strlen		=Keyword
strcmp		=Keyword
strcat		=Keyword
strchr		=Keyword
dp87		=Keyword
idcvt		=Keyword
ldcvt		=Keyword
ifcvt		=Keyword
lfcvt		=Keyword
vfcvt		=Keyword
vdcvt		=Keyword
ufcvt		=Keyword
udcvt		=Keyword
ducvt		=Keyword
fucvt		=Keyword
dvcvt		=Keyword
fvcvt		=Keyword
dicvt		=Keyword
dlcvt		=Keyword
ficvt		=Keyword
flcvt		=Keyword
fdcvt		=Keyword
dfcvt		=Keyword
buildptr	=Keyword
sqrt		=Keyword
sin		=Keyword
cos		=Keyword
log		=Keyword
fsincos		=Keyword
fabs		=Keyword
getflags	=Keyword
setflags	=Keyword
setrealmode	=Keyword
cleartaskswitchedflag	=Keyword
setmachinestatus	=Keyword
atan2		=Keyword
atan		=Keyword
pushf		=Keyword
popf		=Keyword
causeinterrupt	=Keyword
lockset		=Keyword
halt		=Keyword
waitforinterrupt =Keyword
gettaskregister	=Keyword
settaskregister	=Keyword
saveglobaltable	=Keyword
restoreglobaltable =Keyword
saveinterrupttable =Keyword
restoreinterrupttable =Keyword
getlocaltable	=Keyword
setlocaltable	=Keyword
getmachinestatus =Keyword
getsegmentlimit =Keyword
segmentreadable	=Keyword
segmentwritable	=Keyword
getaccessrights	=Keyword
adjustrpl	=Keyword
initrealmathunit =Keyword
getrealerror	=Keyword
saverealstatus	=Keyword
restorerealstatus =Keyword
get_reg_eax	=Keyword
get_reg_ebx	=Keyword
get_reg_ecx	=Keyword
get_reg_edx	=Keyword
get_reg_esi	=Keyword
get_reg_edi	=Keyword
get_reg_ebp	=Keyword
get_reg_esp	=Keyword
set_reg_eax	=Keyword
set_reg_ebx	=Keyword
set_reg_ecx	=Keyword
set_reg_edx	=Keyword
set_reg_esi	=Keyword
set_reg_edi	=Keyword
set_reg_ebp	=Keyword
set_reg_esp	=Keyword
pushall		=Keyword
popall		=Keyword
f2xm1		=Keyword
get_reg_ds	=Keyword
get_reg_cs	=Keyword
get_reg_es	=Keyword
get_reg_ss	=Keyword
get_reg_fs	=Keyword
get_reg_gs	=Keyword
set_reg_ds	=Keyword
set_reg_cs	=Keyword
set_reg_es	=Keyword
set_reg_ss	=Keyword
set_reg_fs	=Keyword
set_reg_gs	=Keyword
getcontrolregister =Keyword
setcontrolregister =Keyword
getdebugregister =Keyword
setdebugregister =Keyword
gettestregister =Keyword
settestregister =Keyword
fstcw		=Keyword
fclex		=Keyword
fstenv		=Keyword
finit		=Keyword
fldcw		=Keyword
fstsw		=Keyword
selector__1	=Keyword
reverse_byte_order        =Keyword
invalidatedatacache =Keyword
wbinvalidatedatacache =Keyword
invalidatetlbentry =Keyword
dxcvt		=Keyword
fxcvt		=Keyword
dycvt		=Keyword
fycvt		=Keyword
xdcvt		=Keyword
xfcvt		=Keyword
ydcvt		=Keyword
yfcvt		=Keyword
farptr16	=Keyword
farptr32	=Keyword
swap_word	=Keyword
swap_long	=Keyword
farptr48        =Keyword
nop		=Keyword
clearcarryflag	=Keyword
setcarryflag	=Keyword
cleardirectionflag =Keyword
setdirectionflag =Keyword
push            =Keyword
pop             =Keyword
_inline         =Keyword

