; ----------------------------------------------------------------------------
; MARVELL INTERNATIONAL LTD., ON BEHALF OF ITSELF AND ITS WORLDWIDE 
; AFFILIATES(COLLECTIVELY, "MARVELL"), MAKES NO WARRANTY OF ANY KIND WITH 
; REGARD TO THIS MATERIAL, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES 
; OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
; MARVELL ASSUMES NO RESPONSIBILITY FOR ANY ERRORS THAT MAY
; APPEAR IN THIS DOCUMENT. MARVELL MAKES NO COMMITMENT TO
; UPDATE NOR TO KEEP CURRENT THE INFORMATION CONTAINED IN THIS DOCUMENT.
; ----------------------------------------------------------------------------
[Parser]
Operators = 
Delimiters = 
KWStartChars = 
KWMiddleChars =
KWEndChars =
NumTags =0

[Tag1]
ColorGroup = Comment
BeginTag = /*
EndTag = */
MultiLine = 1

[Tag2]
ColorGroup = String
BeginTag = "
EndTag="
MultiLine=0
EscapeChar=\

[Tag3]
ColorGroup = String
BeginTag = '
EndTag = '
MultiLine=0
EscapeChar=\

[Tag4]
ColorGroup = Comment
BeginTag = //
EndTag = 
MultiLine=0

[Editor]
TabSize =4
AutoIndent =0
ShowWhitespace =0
VirtualWhitespace =0
ReplaceTabs =0
MatchCase =1

[Font]
FaceName =Courier
Size =10
Italic =0
Bold =0

[ColorGroups]
NumGroups =4
Group1 =Text
Group2 =Text Selection
Group3 =Number
Group4 =Operator
Group5 = Comment
Group6 = Keyword
Group7 = String

[Text]
Foreground =0,0,0
Background =255,255,255
DisplayName =Text
Configurable =1
BackColorAutomatic =1
ForeColorAutomatic =1

[Text Selection]
Foreground =255,255,255
Background =0,0,0
BackColorAutomatic =1
ForeColorAutomatic =1
DisplayName=Text Selection
Configurable=1

[Number]
Foreground =0,0,0
Background =255,255,255
BackColorAutomatic =1
ForeColorAutomatic =1
DisplayName=Number
Configurable=0

[Operator]
Foreground =0,0,0
Background =255,255,255
BackColorAutomatic =1
ForeColorAutomatic =1
DisplayName=Operator
Configurable=0


[Keyword]
Foreground = 0,0,255
Background = 255,255,255
BackColorAutomatic = 1
ForeColorAutomatic=0
DisplayName=Keyword
Configurable=1

[Comment]
Foreground = 0,128,0
Background = 255,255,255
BackColorAutomatic = 1
ForeColorAutomatic=0
DisplayName=Comment
Configurable=1

[String]
Foreground = 0,0,0
Background = 255,255,255
BackColorAutomatic = 1
ForeColorAutomatic = 1
DisplayName=String
Configurable=1

[Keywords]
